### ISSUE TITLE
Missing collection : community.crypto

### ISSUE THREAD

**Issue by Ricker42** [kubealex/libvirt-ocp4-provisioner#25]
Working on pull from 2021/11/08 13:00 Eastern.

Attempting to run on RHEL8 server.

After installing ansible from the ansible-automation-platform-2.0-early-access-for-rhel-8-x86_64-rpms available via a Red Hat Developer subscription, I ran the 'ansible-galaxy collection install -r requirements.yml' command.

As I'm running this on a single server, I chose the 'ansible-playbook main-sno.yml' command next.  It failed with message "ERROR! couldn't resolve module/action 'openssh_keypair'. This often indicates a misspelling, missing collection, or incorrect module path."

I found the collection "community.crypto" on galaxy.ansible.com and added it to the requirements.yml file, re-ran that then re-rain main-sno.yml and got past the error.

Newbie to GitHub so didn't want to even try to figure out if it was possible to submit the change, thought this was safest.

**Comment by kubealex** [comment]
Hi! I notice you are using RHEL8 but at this time I still didn't have the chance to test against it. If you manage to reach the end of the setup, please fork this repository, create a branch on your side with the working configuration and submit it via a pull request, so we can test it together and merge it if it is working!

**Comment by Ricker42** [comment]
I've been working with a Red Hat TAM who has done exactly that.  I'm going to be testing his fork today.

**Comment by kubealex** [comment]
Please retry pulling new modifications on master!
