### ISSUE TITLE
 next_nth_usable filter requires python's netaddr be installed on the ansible controller

### ISSUE THREAD

**Issue by Ricker42** [kubealex/libvirt-ocp4-provisioner#26]
I'm getting this error during the "Configure NetworkManager for libvirt network" task.  I've installed python3_netaddr on the base server, but this still comes up.  Full -vvv output from the relevant section of the playbook:

`TASK [Configure NetworkManager for libvirt network] *****************************************************************************************************************************************************************
task path: /images/libvirt-ocp4-provisioner-master/70_setup_sno_cluster.yml:80
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1636499160.5299973-58778-194397503289046 `" && echo ansible-tmp-1636499160.5299973-58778-194397503289046="` echo /root/.ansible/tmp/ansible-tmp-1636499160.5299973-58778-194397503289046 `" ) && sleep 0'
redirecting filter ansible.builtin.next_nth_usable to ansible.netcommon.next_nth_usable
redirecting filter ansible.builtin.next_nth_usable to ansible.netcommon.next_nth_usable
redirecting filter ansible.builtin.next_nth_usable to ansible.netcommon.next_nth_usable
redirecting filter ansible.builtin.next_nth_usable to ansible.netcommon.next_nth_usable
redirecting filter ansible.builtin.next_nth_usable to ansible.netcommon.next_nth_usable
redirecting filter ansible.builtin.next_nth_usable to ansible.netcommon.next_nth_usable
redirecting filter ansible.builtin.next_nth_usable to ansible.netcommon.next_nth_usable
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1636499160.5299973-58778-194397503289046/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/plugins/action/template.py", line 146, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 1100, in do_template
    res = j2_concat(rf)
  File "<template>", line 16, in root
  File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 265, in wrapper
    ret = func(*args, **kwargs)
  File "/root/.ansible/collections/ansible_collections/ansible/netcommon/plugins/filter/ipaddr.py", line 1125, in _need_netaddr
    raise errors.AnsibleFilterError(
ansible.errors.AnsibleFilterError: The next_nth_usable filter requires python's netaddr be installed on the ansible controller
fatal: [localhost]: FAILED! => {
    "changed": false,
    "msg": "AnsibleFilterError: The next_nth_usable filter requires python's netaddr be installed on the ansible controller"
}
`

**Comment by kubealex** [comment]
Hey, thx for raising this up.
what OS are you using?

**Comment by Ricker42** [comment]
Sorry, forgot to say.  I'm running this on RHEL8.4

**Comment by kubealex** [comment]
Can you please post the output for 
`ansible --version`

I just tried to run it on my rhel84 and rhel85 and no error is happening, I was able to install it.

**Comment by Ricker42** [comment]
[root@lab1 openshift-baremetal-install]# ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]

**Comment by Ricker42** [comment]
FYI: I have successfully gotten it all to work...rather I should say the TAM at RedHat I've been working with got it to work in his lab, and I ran his version.  There's something I want to suggest adding to his fork before he submits it back to you.

**Comment by kubealex** [comment]
Please retry pulling new modifications on master!

**Comment by carljmosca** [comment]
This issue seems to have resurfaced with the latest version of RHEL 8.6 and ansible 2.12.2 (ansible-core-2.12.2-3.1.el8.x86_64)
