### ISSUE TITLE
Add support to RHEL

### ISSUE THREAD

**Issue by kubealex** [kubealex/libvirt-ocp4-provisioner#28]
In order to extend capable hosts, add RHEL to the OSes that can be used on the host machine.

**Comment by Ricker42** [comment]
This fork has worked: https://github.com/cptmorgan-rh/libvirt-ocp4-provisioner

This is the one I mentioned in the comment on the netaddr issue.

**Comment by kubealex** [comment]
That's not related to your error, btw. I am working also on that but there's something else I need to double check..that modification would break resolution on hosts using dnsmasq.

**Comment by kubealex** [comment]
Pull request #30 addresses #19 #25 #26
