### ISSUE TITLE
playbook is not really remote host compatible - tested with sno part

### ISSUE THREAD

**Issue by tomazb** [kubealex/libvirt-ocp4-provisioner#31]
Hello!

Wanted to use SNO deploy from Fedora 34 machine to RHEL 8.5 host, but it always failed in Terraform part:

TASK [Use TF project to ensure pool and network are defined] **************************************************************************
fatal: [remote.host]: FAILED! => {"changed": false, "msg": "Path for Terraform project 'terraform/libvirt-resources' doesn't exist on this host - check the path and try again please."}

Local invocation works fine.

Used the sources from today.

Also I noticed I had to copy sno_vars.yml to cluster_vars.yml - otherwise my domain from sno_vars.yml was not being used. Instead default hetzner.lab was used.

Here is the whole install log:
[user@machine libvirt-ocp4-provisioner]$ ansible-playbook -i inventory  main-sno.yml

PLAY [This play ensures prerequisites are satisfied before installing] ****************************************************************

TASK [Gathering Facts] ****************************************************************************************************************
ok: [remote.host]

TASK [Check if distribution is supported] *********************************************************************************************
skipping: [remote.host]

TASK [fail] ***************************************************************************************************************************
skipping: [remote.host]

TASK [fail] ***************************************************************************************************************************
skipping: [remote.host]

TASK [Fail fast if bootstrap node doesn't meet minimum requirements] ******************************************************************
skipping: [remote.host]

TASK [Check for pullSecret variable and fail fast] ************************************************************************************
skipping: [remote.host]

PLAY [This play installs needed tools to provision infrastructure VMs] ****************************************************************

TASK [Gathering Facts] ****************************************************************************************************************
ok: [remote.host]

TASK [Install needed packages] ********************************************************************************************************
ok: [remote.host]

TASK [Install needed packages] ********************************************************************************************************
skipping: [remote.host]

TASK [Install needed packages] ********************************************************************************************************
skipping: [remote.host]

TASK [Install needed packages] ********************************************************************************************************
skipping: [remote.host]

TASK [Download and provision Terraform] ***********************************************************************************************
ok: [remote.host]

TASK [Virtualization services are enabled] ********************************************************************************************
ok: [remote.host]

TASK [Use TF project to ensure pool and network are defined] **************************************************************************
fatal: [remote.host]: FAILED! => {"changed": false, "msg": "Path for Terraform project 'terraform/libvirt-resources' doesn't exist on this host - check the path and try again please."}

PLAY RECAP ****************************************************************************************************************************
remote.host           : ok=5    changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0

**Comment by kubealex** [comment]
Thank you for reporting it. That was added before the provisioner created vms, there are a lot of potential issues (DNS and terraform being only a couple) to really support remote hosts. 

Feel free to add your contribution to start implementing this feature in the future :)
